apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-new
  labels:
    app: be
spec:
  replicas: 3
  selector:
    matchLabels:
      app: be
  template:
    metadata:
      labels:
        app: be
    spec:
      containers:
      - name: appjarcont
        image: abhishekbudruk007/webapp:v6
        env:
          - name: DATABASE_HOST
            value: 'mysql'
          - name: DATABASE_USER
            value: 'root'
          - name: DATABASE_PASSWORD
            value: 'root'
          - name: DATABASE_PORT
            value: '3306'
        ports:
         - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: websvc
spec:
  loadBalancerIP: 172.31.27.253
  type: LoadBalancer
  selector:
    app: be
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      #nodePort: 30001
